## Optimal Policies and Optimal Value Functions:

Solving a reinforcement learning tarsk means roughly finding a policy that achieves a lot of reward over the long run. For finite MDPs, we can precisely define an optimal policy in the following way.

Value functions define a partial ordering over policies. A policy $\pi$ is defined to be better than the equal to a policy $\pi'$, if its expected return is greater than or equal to that of $\pi'$ for all states. In other words, $\pi \geq \pi'$ if and only if $v_\pi(s) \geq v_{\pi'}(s)$ for all $s \in S$. There is always atleast one policy that is better than or equal to all other policies. This is an **optimal policy**. Although there may be more than one, we denote all the optimal policies by $\pi_*$. They share the same state-value function, called the optimal state-value function, denoted $v_*$, and defined as

$$ \large v_*(s) \doteq \underset {\pi}{max} \space v_\pi(s)$$
</p>
for all $s \in S$

Optimal policies also share the same **optimal action-value function**, denated $q_*$, and defined as

$$\large q_* \doteq \underset {\pi}{max} \space q_\pi(s,a)$$

for all $s \in S$ and $a \in A(s)$

For the state-action pair(s,a), this function gives the expected return for taking action $a$ in state $s$ and thereafter following an optimal policy. Thus, we can write $q_*$ in terms of $v)*$ as follows.

$$\large q_*(s,a) =  \mathbb{E}[R_{t+1} + \gamma  v_*(S_{t+1})\space | \space S_t=s, A_t=a]$$

Because $v_x$ is the value function for a policy, it must satisfy the self-consistency condtion given by the Bellman equation for state values. Buecause it is the optimal value function, however, $v_*$'s consistency condition can be written in a special form without reference to any specific policy. This is the Bellman equation for $v_*$, or the **Bellman optimality equation**. Intutively, the Bellman optimality equation expresses the fact that the value of a state under an optimal policy must equal the expected return for the best action from that state.

$\large v_*(s) = \underset {a \in A(s)}{max} \space q_{\pi_*}(s,a)$
</p>

$\large  = \underset{a}{max}\mathbb{E}_{\pi_*}[G_t \space | \space S_t=s, A_t=a]$

$\large  = \underset{a}{max}\mathbb{E}_{\pi_*}[R_{t+1} + \gamma G_{t+1} \space | \space S_t=s, A_t=a]$

$\large  = \underset{a}{max}\mathbb{E}_{\pi_*}[R_{t+1} + \gamma v_*(S_{t+1}) \space | \space S_t=s, A_t=a] \rightarrow (3.18)$

$\large  = \underset{a}{max} \sum_{s',r'} p(s',r \space | \space s,a)\big[ r + \gamma v_*(s')\big] \rightarrow (3.19)$

the last two equations are two forms of the Bellman optimality equation for $v_*$. The Bellman optimailty equation for $q_*$ is

$$\large q_*(s,a) = \mathbb{E}\Big[ R_{t+1} + \gamma \space \underset {a'}{max} \space q_*(S_{t+1},a') \space | \space S_t =s, A_t=a \Big]$$
$$\large =\sum_{s',r}p(s',r |s,a)\Big[ r + \gamma \space \underset {a'}{max} \space q_*(s',a')\Big] \rightarrow (3.20)$$

For finite MDPs, the Bellman optimality equation for $v_*$ (3.19) has a unique solution. The Bellman optimality equation is actually a system of equations, one for each state, so if there are n states, then there are $n$ equations in $n$ unknowns. If the dynamics $p$ of the environment are known, then in principle once can solve this system of equations for $v_*$ using any one of variety of methods for solving systems of nonlinear equations. One can solve a related set of equations for $q_*$

Once one has $v_*$, it is relatively easy to determine an optimal policy. For each state $s$, there will be one or more actions at which the maximum is obtained in the Bellman optimality equation. Any policy that assigns nonzero probability only to these actions is an optimal policy. You can think of this as one-step search.
If you have the optimal value function, $v_*$, then the actions that appear best after a one-step search will be optimal actions.
Another way of saying this is that any policy that is **greedy** with respect to the optimal evaluation function $v_*$ is an optimal policy.

The term **greedy** is used in computer science to describe any search or decision procedure that selects alternatives based only on local or immediate considerations, without considering the possibility that such selection my prevent future access to even better alternatives. Consequently, it describes policies that select actions based only on their short-term consequences. The beauty of $v_*$ is that if one uses it to evaluate the short-term consequences of actions-specifically, the one-step consequences, then a greedy policy is actually optimal in the long-term sense in which we are interested because $v_*$ already takes into account the reward consequences of all possible future behaviour. Bye means of $v_*$, the optimal expected long-term return is turned into a quantity that is locally and immediately available for each state. Hence, a one-step-ahead search yeilds the long-term optimal actions.

Having $q_*$ makes choosing optimal actions even easier. With $q_*$, the agent does not even have to do a one-step-ahead search. For any state $s$, it can simply find any action that maximizes $q_*(s,a). The action-value function effectively caches the results of all one-step-ahead searches. It provides the optimal expected long-term return as a vlaue that is locally and immediately available for each state-action pair. Hence, at the cost of representing a function of state-action pairs, instread of just of states, the optimal action-value function allows optimal actions to be selected without having to know anything about possible successor states and their values, that is without having to know anything about the environment's dynamics

**Exercise 3.24**
</p>
Gives the optimal value of the best state of the gridworld as
24.4, to one decimal place. Use your knowledge of the optimal policy and (3.8) to express
this value symbolically, and then to compute it to three decimal places.

In [1]:
import numpy as np

In [2]:
WORLD_SIZE = 5

A_POS = [0,1]
B_POS = [0,3]

A_PRIME_POS = [4,1]
B_PRIME_POS = [2,3]

A_TO_APRIME_TRANSITION_REWARD = 10
B_TO_BPRIME_TRANSITION_REWARD = 5

Gamma = 0.9

# left, up, right down
Actions =[np.array([0,-1]),
          np.array([-1,0]),
          np.array([0,1]),
          np.array([1,0])]

#In the problem it is given that actions are equiprobable.
#1/4 = 0.25
ACTION_PROB =  1/len(Actions)

In [19]:
def Step(state, action):
    
    if state == A_POS:
        return A_PRIME_POS, A_TO_APRIME_TRANSITION_REWARD
    elif state == B_POS:
        return B_PRIME_POS, B_TO_BPRIME_TRANSITION_REWARD
    else:
        state = np.array(state)
        next_state = state + action
        x, y = next_state
        if x < 0 or x >= WORLD_SIZE or y < 0 or y >= WORLD_SIZE:
            reward = -1
            next_state = state
        else :
            reward = 0
        return next_state, reward

In [23]:
values = np.zeros((WORLD_SIZE,WORLD_SIZE))
values, values.shape
count = 0
while True:
    # keep iterating until convergence
    count += 1
    new_value = np.zeros(values.shape,)
    for i in range(0, WORLD_SIZE):
        for j in range(0, WORLD_SIZE):
            all_val = []
            for action in Actions:
                (next_i, next_j), reward = Step([i,j], action)
                # value iteration
                all_val.append(reward + Gamma * values[next_i,next_j])
            new_value[i,j] = np.max(all_val)
    if np.sum(np.abs(values - new_value)) < 1e-4:
        print(f'Value got converged after {count} iterations')
        print(values)
        break
    values = new_value
    #print(values)

Value got converged after 124 iterations
[[21.97744338 24.41938153 21.97744338 19.41938153 17.47744338]
 [19.77969904 21.97744338 19.77969904 17.8017056  16.02153504]
 [17.8017056  19.77969904 17.8017056  16.02153504 14.41938153]
 [16.02153504 17.8017056  16.02153504 14.41938153 12.97744338]
 [14.41938153 16.02153504 14.41938153 12.97744338 11.67969904]]
